version: "3.8"
services:
  api:
    entrypoint: ["java","-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n","-jar","app.jar"]
    ports:
      - 5005:5005
      - "${DF_API_PORT:-8080}:${DF_API_PORT:-8080}"