services:
  # The user, entrypoint, and command settings for the database containers in
  # docker-compose.yaml cause "Operation not permitted" errors in CI related to
  # changing ownership or permissions. In this file, we reset those settings to
  # use what is configured in the underlying postgres image.
  db:
    user: !reset
    entrypoint: !reset
    command: !reset

  mef-apps-db:
    user: !reset
    entrypoint: !reset
    command: !reset

  state-api-db:
    user: !reset
    entrypoint: !reset
    command: !reset

  email-service-db:
    user: !reset
    entrypoint: !reset
    command: !reset
