spring.profiles.group:
  development:
    - "cors-permit-all"
    - "default-security"
    - "enable-development-identity-supplier"
    - "enable-remote-cache"
    - "allow-authentication-without-pii"
    - "local"
    - "mock"

spring:
  threads:
    virtual:
      enabled: false
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:${DF_DB_PORT:5432}/directfile
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog.yaml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  data:
    redis:
      client-type: lettuce # options: lettuce, jedis (default is auto-detection from classpath)

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      discovery:
        enabled: false
      exposure:
        include: health

logging:
  config: classpath:logback-minimal.xml

server:
  port: ${DF_API_PORT:8080}
  shutdown: graceful
  error:
    include-message: always
  servlet:
    context-path: "${DF_API_PUBLIC_PATH:/df/file/api}"
  max-http-request-header-size: 16384

direct-file:
  api-version: v1
  referer-header:
    allowed-prefixes:
      - http://localhost:3000/
      - http://localhost:5000/df/file/
      - http://host.docker.internal:3000/
      - http://host.docker.internal:5000/df/file/
    block-mode-enabled: true
  max_dispatch_enqueue_attempts: 2
  loader:
    load-at-startup: true
    fact-dictionary-xml-pattern: "classpath:/tax/*.xml"
  state-api:
    base-url: http://localhost:${STATEAPI_PORT:8081}/state-api
    version: "1"
    v2-auth-token-path: "/v2/authorization-token"
  status-endpoint:
    # this is a failing request back to this server (override it in another profile for status to work)
    status-endpoint-uri: http://127.0.0.1:8080/status
    rejection-codes-endpoint-uri: http://127.0.0.1:8080/status/rejection-codes
  submit-endpoint:
    submit-endpoint-uri: http://127.0.0.1:${DF_SUBMIT_PORT:8083}/validate
  pdfs:
    output-location-type: directory
    output-location: "/output/pdfs/"
    useDocumentStorageForPilotYear: false
    configured-pdfs:
      - name: IRS1040S8812
        year: 2024
        language-code: en
        location: pdf/2024/IRS1040S8812/en/f1040s8_accessible.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040S8812/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040S8812
        year: 2024
        language-code: es
        location: pdf/2024/IRS1040S8812/es/f1040s8s_accessible.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040S8812/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: FORM9000
        year: 2024
        language-code: en
        location: pdf/2024/FORM9000/en/f9000_2021.pdf
        location-type: classpath
        configuration-location: pdf/2024/FORM9000/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: FORM9000
        year: 2024
        language-code: es
        location: pdf/2024/FORM9000/es/f9000sp_2021.pdf
        location-type: classpath
        configuration-location: pdf/2024/FORM9000/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040S1
        year: 2024
        language-code: en
        location: pdf/2024/IRS1040S1/en/f1040s1.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040S1/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040S1
        year: 2024
        language-code: es
        location: pdf/2024/IRS1040S1/es/f1040s1s.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040S1/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040S2
        year: 2024
        language-code: en
        location: pdf/2024/IRS1040S2/en/f1040s2.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040S2/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040S2
        year: 2024
        language-code: es
        location: pdf/2024/IRS1040S2/es/f1040s2s.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040S2/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040S3
        year: 2024
        language-code: en
        location: pdf/2024/IRS1040S3/en/f1040s3.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040S3/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040S3
        year: 2024
        language-code: es
        location: pdf/2024/IRS1040S3/es/f1040s3s.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040S3/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040SB
        year: 2024
        language-code: en
        location: pdf/2024/IRS1040SB/en/f1040sb_accessible.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040SB/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040EIC
        year: 2024
        language-code: en
        location: pdf/2024/IRS1040EIC/en/f1040sei-p.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040EIC/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040EIC
        year: 2024
        language-code: es
        location: pdf/2024/IRS1040EIC/es/f1040sep-p.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040EIC/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRSW2
        year: 2024
        language-code: en
        location: pdf/2024/IRSW2/en/fw2.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRSW2/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040
        year: 2024
        language-code: en
        location: pdf/2024/IRS1040/en/f1040.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040
        year: 2024
        language-code: es
        location: pdf/2024/IRS1040/es/f1040sp.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040SR
        year: 2024
        language-code: en
        location: pdf/2024/IRS1040SR/en/f1040s-p.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040SR/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS1040SR
        year: 2024
        language-code: es
        location: pdf/2024/IRS1040SR/es/f1040srs-p.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS1040SR/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: DEPENDENTS_STATEMENT
        year: 2024
        language-code: en
        location: pdf/2024/DEPENDENTS_STATEMENT/en/1040_AdditionalDependents.pdf
        location-type: classpath
        configuration-location: pdf/2024/DEPENDENTS_STATEMENT/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: DEPENDENTS_STATEMENT
        year: 2024
        language-code: es
        location: pdf/2024/DEPENDENTS_STATEMENT/es/1040_Dependientes_Adicionales.pdf
        location-type: classpath
        configuration-location: pdf/2024/DEPENDENTS_STATEMENT/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: SCHEDULE_LEP
        year: 2024
        language-code: en
        location: pdf/2024/SCHEDULE_LEP/en/f1040lep-p.pdf
        location-type: classpath
        configuration-location: pdf/2024/SCHEDULE_LEP/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: SCHEDULE_LEP
        year: 2024
        language-code: es
        location: pdf/2024/SCHEDULE_LEP/es/f1040les-p.pdf
        location-type: classpath
        configuration-location: pdf/2024/SCHEDULE_LEP/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: SCHEDULE_R
        year: 2024
        language-code: en
        location: pdf/2024/SCHEDULE_R/en/f1040sr_accessible.pdf
        location-type: classpath
        configuration-location: pdf/2024/SCHEDULE_R/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS8862
        year: 2024
        language-code: en
        location: pdf/2024/IRS8862/en/f8862_accessible.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS8862/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS8862
        year: 2024
        language-code: es
        location: pdf/2024/IRS8862/es/f8862sp_accessible.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS8862/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS8880
        year: 2024
        language-code: en
        location: pdf/2024/IRS8880/en/f8880_accessible-p.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS8880/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS8889
        year: 2024
        language-code: en
        location: pdf/2024/IRS8889/en/f8889_accessible.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS8889/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS8962
        year: 2024
        language-code: en
        location: pdf/2024/IRS8962/en/f8962.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS8962/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: CTC_DEPENDENTS_STATEMENT
        year: 2024
        language-code: en
        location: pdf/2024/CTC_DEPENDENTS_STATEMENT/en/Additional_statement_for_Form_8862_-_Additional_Child_Tax_Credit.pdf
        location-type: classpath
        configuration-location: pdf/2024/CTC_DEPENDENTS_STATEMENT/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: CTC_DEPENDENTS_STATEMENT
        year: 2024
        language-code: es
        location: pdf/2024/CTC_DEPENDENTS_STATEMENT/es/SPANISH_Additional_statement_for_Form_8862_-_Additional_Child_Tax_Credit.pdf
        location-type: classpath
        configuration-location: pdf/2024/CTC_DEPENDENTS_STATEMENT/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: ODC_DEPENDENTS_STATEMENT
        year: 2024
        language-code: en
        location: pdf/2024/ODC_DEPENDENTS_STATEMENT/en/Additional_statement_for_Form_8862_-_Credit_for_other_dependents.pdf
        location-type: classpath
        configuration-location: pdf/2024/ODC_DEPENDENTS_STATEMENT/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: ODC_DEPENDENTS_STATEMENT
        year: 2024
        language-code: es
        location: pdf/2024/ODC_DEPENDENTS_STATEMENT/es/SPANISH_Additional_statement_for_Form_8862_-_Credit_for_other_dependents.pdf
        location-type: classpath
        configuration-location: pdf/2024/ODC_DEPENDENTS_STATEMENT/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS2441
        year: 2024
        language-code: en
        location: pdf/2024/IRS2441/en/f2441.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS2441/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: IRS2441_DUE_DILIGENCE_STATEMENT
        year: 2024
        language-code: en
        location: pdf/2024/IRS2441_DUE_DILIGENCE_STATEMENT/en/irs2441_due_diligence_statement.pdf
        location-type: classpath
        configuration-location: pdf/2024/IRS2441_DUE_DILIGENCE_STATEMENT/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: DF1099R
        year: 2024
        language-code: en
        location: pdf/2024/DF1099R/en/DF1099Ren.pdf
        location-type: classpath
        configuration-location: pdf/2024/DF1099R/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: DF1099R
        year: 2024
        language-code: es
        location: pdf/2024/DF1099R/es/DF1099Res.pdf
        location-type: classpath
        configuration-location: pdf/2024/DF1099R/es/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: CDCC_QUALIFYING_PERSON_STATEMENT
        year: 2024
        language-code: en
        location: pdf/2024/CDCC_QUALIFYING_PERSON_STATEMENT/en/irs2441_qualifying_persons_statement.pdf
        location-type: classpath
        configuration-location: pdf/2024/CDCC_QUALIFYING_PERSON_STATEMENT/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
      - name: CDCC_CAREGIVERS_STATEMENT
        year: 2024
        language-code: en
        location: pdf/2024/CDCC_CAREGIVERS_STATEMENT/en/2441_Additional-Care-Providers.pdf
        location-type: classpath
        configuration-location: pdf/2024/CDCC_CAREGIVERS_STATEMENT/en/configuration.yml
        configuration-location-type: classpath
        cache-in-memory: true
  pii-service:
    enabled: false
  user-details-cache:
    max-items: 500 # only applies to in-memory cache
    expire-after-write: 1h
  status-response-body-cache:
    max-items: 500 # only applies to in-memory cache
    expire-after-write: 1h
  s3-notification-event-cache:
    max-items: 50000
    fixedDelayMilliseconds: 200000
    batch-size: 50
  aws:
    default-credentials-provider-chain-enabled: false
    region: us-west-2
    credentials:
      accessKey: accessKey
      secretKey: secretKey
    messageQueue:
      dispatch-queue: dispatch-queue
      status-change-queue: status-change-queue
      dlq-status-change-queue: dlq-status-change-queue
      submission-confirmation-queue: submission-confirmation-queue
      dlq-submission-confirmation-queue: dlq-submission-confirmation-queue
      s3-notification-event-queue: s3-notification-event-queue
      dlq-s3-notification-event-queue: dlq-s3-notification-event-queue
      send-email-queue: send-mail
      data-import-request-queue: data-import-request-queue
      dlq-data-import-request-queue: dlq-data-import-request-queue
      data-import-result-queue: data-import-result-queue
      dlq-data-import-result-queue: dlq-data-import-result-queue
      endpoint: http://localhost:4566
      sqs-message-handling-enabled: true
      sqs-message-sending-enabled: true
    sns:
      endpoint: http://localhost:4566
      submission-confirmation-topic-arn: arn:aws:sns:us-west-2:000000000000:submission-confirmation-topic
      submission-confirmation-publish-enabled: true
      region: us-west-2
    s3:
      endpoint: http://s3.localhost.localstack.cloud:4566/
      bucket: direct-file-taxreturns
      operations-jobs-bucket: operations-jobs
      feature-flags-bucket: direct-file-taxreturns
      feature-flags-object: "feature-flags.json"
      feature-flags-expiration: 15m
      data-import-gating-bucket: ${direct-file.aws.s3.operations-jobs-bucket:operations-jobs}
      data-import-gating-object: "data-import-gating.json"
      data-import-gating-expiration: 15m
      environment-prefix:
      assume-role-arn: assume-role-arn-placeholder
      assume-role-session-name: "df-backend"
      assume-role-duration-seconds: "1800"
    elasticache:
      endpoint: http://localhost:4566
      kms-key-arn: "elasticache-kms-key-arn"
    ses:
      endpoint: http://localhost:4566
      region: us-west-2
      identity-arn: "ses-identity-arn"
      identity-email: "ses-identity-email@test.com"
  fact-graph-service:
    facts-for-xml-location: "/factgraphservice/xmlFactPaths"
  data-import-gating:
    allowlist:
      enabled: false
      hex-key:
      object-key: "data-import-allowlist-export.csv"
  data-import:
    enabled: true
  feature-flags:
    allowlist:
      enabled: false
      hex-key: "key"
      object-key: "allowlist-export.csv"
    open-enrollment:
      enabled: true
      scheduler:
        cron: "-"
        fixedDelayMilliseconds: ""
    state-api:
      exported-facts:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs

aws:
  default-credentials-provider-chain-enabled: false
  crypto-cache:
    # maximum number of messages that can be encrypted with a cached key
    message-use-limit: 200
    # seconds before expiration
    max-age-seconds: 3600
    # maximum number of items in the cache
    max-items: 500

openfeature-starter:
    s3-provider:
        environment-prefix:
        bucket: ${direct-file.aws.s3.bucket}
        expiration: 15m
