name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - openfile
  pull_request:
    branches:
      - openfile

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Install sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            direct-file/df-client/**/package-lock.json

      - name: Build fact graph
        run: |
          cd direct-file/fact-graph-scala
          sbt +test fullOptJS
          sbt publishLocal

      - name: Run backend tests
        run: |
          cd direct-file/backend
          ./mvnw -B install
          ./mvnw -B verify

      - name: Run frontend tests
        run: |
          cd direct-file/df-client/df-client-app
          npm ci
          npm run lint
          npm run test -- --watch=false
          npm run build